site_name: kVIS3 Documentation

nav:
    - Home: 'index.md'
    - User Information: 
        - plotFormat.md
        - plotFcn.md
        - reportFcn.md        
        
    - Developer Information:
        - fdsFormat.md
        - Doxygen Code Documentation (WiP): doxygen/files.html
        
        
        
        
theme: readthedocs

use_directory_urls: false

site_dir: ../docs